# Your Website Title
title: Milzam Wafi Azhar

# Your Website URL
url: 'http://WafiRepo.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Milzam Wafi Azhar
tagline: Data Scientist, Data Analyst, Bussiness Intelligent
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Data Scientist, Data Analyst, Bussiness Intelligent
description_tiny: 'Home: Palembang, South Sumatera | Studied: Natioanl Central University, Taiwan | Work: Computer Science (Research Student)'
email: azharmilzam@gmail.com
website: WafiRepo.github.io # do not add http://
linkedin: milzamwafiazhar
github: WafiRepo
twitter: '@milzamwafiazhar'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
